<?php
/**
 * Countries.
 */

namespace Simple_Sponsorships;

/**
 * Class Countries
 *
 * @package Simple_Sponsorships
 */
class Countries {

	/**
	 * Countries.
	 *
	 * @var array
	 */
	private $countries = array();

	/**
	 * Get all countries.
	 *
	 * @return array
	 */
	public function get_countries() {
		if ( empty( $this->countries ) ) {
			$this->countries = apply_filters( 'ss_countries', array(
				'AF' => __( 'Afghanistan', 'simple-sponsorships' ),
				'AX' => __( '&#197;land Islands', 'simple-sponsorships' ),
				'AL' => __( 'Albania', 'simple-sponsorships' ),
				'DZ' => __( 'Algeria', 'simple-sponsorships' ),
				'AS' => __( 'American Samoa', 'simple-sponsorships' ),
				'AD' => __( 'Andorra', 'simple-sponsorships' ),
				'AO' => __( 'Angola', 'simple-sponsorships' ),
				'AI' => __( 'Anguilla', 'simple-sponsorships' ),
				'AQ' => __( 'Antarctica', 'simple-sponsorships' ),
				'AG' => __( 'Antigua and Barbuda', 'simple-sponsorships' ),
				'AR' => __( 'Argentina', 'simple-sponsorships' ),
				'AM' => __( 'Armenia', 'simple-sponsorships' ),
				'AW' => __( 'Aruba', 'simple-sponsorships' ),
				'AU' => __( 'Australia', 'simple-sponsorships' ),
				'AT' => __( 'Austria', 'simple-sponsorships' ),
				'AZ' => __( 'Azerbaijan', 'simple-sponsorships' ),
				'BS' => __( 'Bahamas', 'simple-sponsorships' ),
				'BH' => __( 'Bahrain', 'simple-sponsorships' ),
				'BD' => __( 'Bangladesh', 'simple-sponsorships' ),
				'BB' => __( 'Barbados', 'simple-sponsorships' ),
				'BY' => __( 'Belarus', 'simple-sponsorships' ),
				'BE' => __( 'Belgium', 'simple-sponsorships' ),
				'PW' => __( 'Belau', 'simple-sponsorships' ),
				'BZ' => __( 'Belize', 'simple-sponsorships' ),
				'BJ' => __( 'Benin', 'simple-sponsorships' ),
				'BM' => __( 'Bermuda', 'simple-sponsorships' ),
				'BT' => __( 'Bhutan', 'simple-sponsorships' ),
				'BO' => __( 'Bolivia', 'simple-sponsorships' ),
				'BQ' => __( 'Bonaire, Saint Eustatius and Saba', 'simple-sponsorships' ),
				'BA' => __( 'Bosnia and Herzegovina', 'simple-sponsorships' ),
				'BW' => __( 'Botswana', 'simple-sponsorships' ),
				'BV' => __( 'Bouvet Island', 'simple-sponsorships' ),
				'BR' => __( 'Brazil', 'simple-sponsorships' ),
				'IO' => __( 'British Indian Ocean Territory', 'simple-sponsorships' ),
				'VG' => __( 'British Virgin Islands', 'simple-sponsorships' ),
				'BN' => __( 'Brunei', 'simple-sponsorships' ),
				'BG' => __( 'Bulgaria', 'simple-sponsorships' ),
				'BF' => __( 'Burkina Faso', 'simple-sponsorships' ),
				'BI' => __( 'Burundi', 'simple-sponsorships' ),
				'KH' => __( 'Cambodia', 'simple-sponsorships' ),
				'CM' => __( 'Cameroon', 'simple-sponsorships' ),
				'CA' => __( 'Canada', 'simple-sponsorships' ),
				'CV' => __( 'Cape Verde', 'simple-sponsorships' ),
				'KY' => __( 'Cayman Islands', 'simple-sponsorships' ),
				'CF' => __( 'Central African Republic', 'simple-sponsorships' ),
				'TD' => __( 'Chad', 'simple-sponsorships' ),
				'CL' => __( 'Chile', 'simple-sponsorships' ),
				'CN' => __( 'China', 'simple-sponsorships' ),
				'CX' => __( 'Christmas Island', 'simple-sponsorships' ),
				'CC' => __( 'Cocos (Keeling) Islands', 'simple-sponsorships' ),
				'CO' => __( 'Colombia', 'simple-sponsorships' ),
				'KM' => __( 'Comoros', 'simple-sponsorships' ),
				'CG' => __( 'Congo (Brazzaville)', 'simple-sponsorships' ),
				'CD' => __( 'Congo (Kinshasa)', 'simple-sponsorships' ),
				'CK' => __( 'Cook Islands', 'simple-sponsorships' ),
				'CR' => __( 'Costa Rica', 'simple-sponsorships' ),
				'HR' => __( 'Croatia', 'simple-sponsorships' ),
				'CU' => __( 'Cuba', 'simple-sponsorships' ),
				'CW' => __( 'Cura&ccedil;ao', 'simple-sponsorships' ),
				'CY' => __( 'Cyprus', 'simple-sponsorships' ),
				'CZ' => __( 'Czech Republic', 'simple-sponsorships' ),
				'DK' => __( 'Denmark', 'simple-sponsorships' ),
				'DJ' => __( 'Djibouti', 'simple-sponsorships' ),
				'DM' => __( 'Dominica', 'simple-sponsorships' ),
				'DO' => __( 'Dominican Republic', 'simple-sponsorships' ),
				'EC' => __( 'Ecuador', 'simple-sponsorships' ),
				'EG' => __( 'Egypt', 'simple-sponsorships' ),
				'SV' => __( 'El Salvador', 'simple-sponsorships' ),
				'GQ' => __( 'Equatorial Guinea', 'simple-sponsorships' ),
				'ER' => __( 'Eritrea', 'simple-sponsorships' ),
				'EE' => __( 'Estonia', 'simple-sponsorships' ),
				'ET' => __( 'Ethiopia', 'simple-sponsorships' ),
				'FK' => __( 'Falkland Islands', 'simple-sponsorships' ),
				'FO' => __( 'Faroe Islands', 'simple-sponsorships' ),
				'FJ' => __( 'Fiji', 'simple-sponsorships' ),
				'FI' => __( 'Finland', 'simple-sponsorships' ),
				'FR' => __( 'France', 'simple-sponsorships' ),
				'GF' => __( 'French Guiana', 'simple-sponsorships' ),
				'PF' => __( 'French Polynesia', 'simple-sponsorships' ),
				'TF' => __( 'French Southern Territories', 'simple-sponsorships' ),
				'GA' => __( 'Gabon', 'simple-sponsorships' ),
				'GM' => __( 'Gambia', 'simple-sponsorships' ),
				'GE' => __( 'Georgia', 'simple-sponsorships' ),
				'DE' => __( 'Germany', 'simple-sponsorships' ),
				'GH' => __( 'Ghana', 'simple-sponsorships' ),
				'GI' => __( 'Gibraltar', 'simple-sponsorships' ),
				'GR' => __( 'Greece', 'simple-sponsorships' ),
				'GL' => __( 'Greenland', 'simple-sponsorships' ),
				'GD' => __( 'Grenada', 'simple-sponsorships' ),
				'GP' => __( 'Guadeloupe', 'simple-sponsorships' ),
				'GU' => __( 'Guam', 'simple-sponsorships' ),
				'GT' => __( 'Guatemala', 'simple-sponsorships' ),
				'GG' => __( 'Guernsey', 'simple-sponsorships' ),
				'GN' => __( 'Guinea', 'simple-sponsorships' ),
				'GW' => __( 'Guinea-Bissau', 'simple-sponsorships' ),
				'GY' => __( 'Guyana', 'simple-sponsorships' ),
				'HT' => __( 'Haiti', 'simple-sponsorships' ),
				'HM' => __( 'Heard Island and McDonald Islands', 'simple-sponsorships' ),
				'HN' => __( 'Honduras', 'simple-sponsorships' ),
				'HK' => __( 'Hong Kong', 'simple-sponsorships' ),
				'HU' => __( 'Hungary', 'simple-sponsorships' ),
				'IS' => __( 'Iceland', 'simple-sponsorships' ),
				'IN' => __( 'India', 'simple-sponsorships' ),
				'ID' => __( 'Indonesia', 'simple-sponsorships' ),
				'IR' => __( 'Iran', 'simple-sponsorships' ),
				'IQ' => __( 'Iraq', 'simple-sponsorships' ),
				'IE' => __( 'Ireland', 'simple-sponsorships' ),
				'IM' => __( 'Isle of Man', 'simple-sponsorships' ),
				'IL' => __( 'Israel', 'simple-sponsorships' ),
				'IT' => __( 'Italy', 'simple-sponsorships' ),
				'CI' => __( 'Ivory Coast', 'simple-sponsorships' ),
				'JM' => __( 'Jamaica', 'simple-sponsorships' ),
				'JP' => __( 'Japan', 'simple-sponsorships' ),
				'JE' => __( 'Jersey', 'simple-sponsorships' ),
				'JO' => __( 'Jordan', 'simple-sponsorships' ),
				'KZ' => __( 'Kazakhstan', 'simple-sponsorships' ),
				'KE' => __( 'Kenya', 'simple-sponsorships' ),
				'KI' => __( 'Kiribati', 'simple-sponsorships' ),
				'KW' => __( 'Kuwait', 'simple-sponsorships' ),
				'KG' => __( 'Kyrgyzstan', 'simple-sponsorships' ),
				'LA' => __( 'Laos', 'simple-sponsorships' ),
				'LV' => __( 'Latvia', 'simple-sponsorships' ),
				'LB' => __( 'Lebanon', 'simple-sponsorships' ),
				'LS' => __( 'Lesotho', 'simple-sponsorships' ),
				'LR' => __( 'Liberia', 'simple-sponsorships' ),
				'LY' => __( 'Libya', 'simple-sponsorships' ),
				'LI' => __( 'Liechtenstein', 'simple-sponsorships' ),
				'LT' => __( 'Lithuania', 'simple-sponsorships' ),
				'LU' => __( 'Luxembourg', 'simple-sponsorships' ),
				'MO' => __( 'Macao S.A.R., China', 'simple-sponsorships' ),
				'MK' => __( 'Macedonia', 'simple-sponsorships' ),
				'MG' => __( 'Madagascar', 'simple-sponsorships' ),
				'MW' => __( 'Malawi', 'simple-sponsorships' ),
				'MY' => __( 'Malaysia', 'simple-sponsorships' ),
				'MV' => __( 'Maldives', 'simple-sponsorships' ),
				'ML' => __( 'Mali', 'simple-sponsorships' ),
				'MT' => __( 'Malta', 'simple-sponsorships' ),
				'MH' => __( 'Marshall Islands', 'simple-sponsorships' ),
				'MQ' => __( 'Martinique', 'simple-sponsorships' ),
				'MR' => __( 'Mauritania', 'simple-sponsorships' ),
				'MU' => __( 'Mauritius', 'simple-sponsorships' ),
				'YT' => __( 'Mayotte', 'simple-sponsorships' ),
				'MX' => __( 'Mexico', 'simple-sponsorships' ),
				'FM' => __( 'Micronesia', 'simple-sponsorships' ),
				'MD' => __( 'Moldova', 'simple-sponsorships' ),
				'MC' => __( 'Monaco', 'simple-sponsorships' ),
				'MN' => __( 'Mongolia', 'simple-sponsorships' ),
				'ME' => __( 'Montenegro', 'simple-sponsorships' ),
				'MS' => __( 'Montserrat', 'simple-sponsorships' ),
				'MA' => __( 'Morocco', 'simple-sponsorships' ),
				'MZ' => __( 'Mozambique', 'simple-sponsorships' ),
				'MM' => __( 'Myanmar', 'simple-sponsorships' ),
				'NA' => __( 'Namibia', 'simple-sponsorships' ),
				'NR' => __( 'Nauru', 'simple-sponsorships' ),
				'NP' => __( 'Nepal', 'simple-sponsorships' ),
				'NL' => __( 'Netherlands', 'simple-sponsorships' ),
				'NC' => __( 'New Caledonia', 'simple-sponsorships' ),
				'NZ' => __( 'New Zealand', 'simple-sponsorships' ),
				'NI' => __( 'Nicaragua', 'simple-sponsorships' ),
				'NE' => __( 'Niger', 'simple-sponsorships' ),
				'NG' => __( 'Nigeria', 'simple-sponsorships' ),
				'NU' => __( 'Niue', 'simple-sponsorships' ),
				'NF' => __( 'Norfolk Island', 'simple-sponsorships' ),
				'MP' => __( 'Northern Mariana Islands', 'simple-sponsorships' ),
				'KP' => __( 'North Korea', 'simple-sponsorships' ),
				'NO' => __( 'Norway', 'simple-sponsorships' ),
				'OM' => __( 'Oman', 'simple-sponsorships' ),
				'PK' => __( 'Pakistan', 'simple-sponsorships' ),
				'PS' => __( 'Palestinian Territory', 'simple-sponsorships' ),
				'PA' => __( 'Panama', 'simple-sponsorships' ),
				'PG' => __( 'Papua New Guinea', 'simple-sponsorships' ),
				'PY' => __( 'Paraguay', 'simple-sponsorships' ),
				'PE' => __( 'Peru', 'simple-sponsorships' ),
				'PH' => __( 'Philippines', 'simple-sponsorships' ),
				'PN' => __( 'Pitcairn', 'simple-sponsorships' ),
				'PL' => __( 'Poland', 'simple-sponsorships' ),
				'PT' => __( 'Portugal', 'simple-sponsorships' ),
				'PR' => __( 'Puerto Rico', 'simple-sponsorships' ),
				'QA' => __( 'Qatar', 'simple-sponsorships' ),
				'RE' => __( 'Reunion', 'simple-sponsorships' ),
				'RO' => __( 'Romania', 'simple-sponsorships' ),
				'RU' => __( 'Russia', 'simple-sponsorships' ),
				'RW' => __( 'Rwanda', 'simple-sponsorships' ),
				'BL' => __( 'Saint Barth&eacute;lemy', 'simple-sponsorships' ),
				'SH' => __( 'Saint Helena', 'simple-sponsorships' ),
				'KN' => __( 'Saint Kitts and Nevis', 'simple-sponsorships' ),
				'LC' => __( 'Saint Lucia', 'simple-sponsorships' ),
				'MF' => __( 'Saint Martin (French part)', 'simple-sponsorships' ),
				'SX' => __( 'Saint Martin (Dutch part)', 'simple-sponsorships' ),
				'PM' => __( 'Saint Pierre and Miquelon', 'simple-sponsorships' ),
				'VC' => __( 'Saint Vincent and the Grenadines', 'simple-sponsorships' ),
				'SM' => __( 'San Marino', 'simple-sponsorships' ),
				'ST' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'simple-sponsorships' ),
				'SA' => __( 'Saudi Arabia', 'simple-sponsorships' ),
				'SN' => __( 'Senegal', 'simple-sponsorships' ),
				'RS' => __( 'Serbia', 'simple-sponsorships' ),
				'SC' => __( 'Seychelles', 'simple-sponsorships' ),
				'SL' => __( 'Sierra Leone', 'simple-sponsorships' ),
				'SG' => __( 'Singapore', 'simple-sponsorships' ),
				'SK' => __( 'Slovakia', 'simple-sponsorships' ),
				'SI' => __( 'Slovenia', 'simple-sponsorships' ),
				'SB' => __( 'Solomon Islands', 'simple-sponsorships' ),
				'SO' => __( 'Somalia', 'simple-sponsorships' ),
				'ZA' => __( 'South Africa', 'simple-sponsorships' ),
				'GS' => __( 'South Georgia/Sandwich Islands', 'simple-sponsorships' ),
				'KR' => __( 'South Korea', 'simple-sponsorships' ),
				'SS' => __( 'South Sudan', 'simple-sponsorships' ),
				'ES' => __( 'Spain', 'simple-sponsorships' ),
				'LK' => __( 'Sri Lanka', 'simple-sponsorships' ),
				'SD' => __( 'Sudan', 'simple-sponsorships' ),
				'SR' => __( 'Suriname', 'simple-sponsorships' ),
				'SJ' => __( 'Svalbard and Jan Mayen', 'simple-sponsorships' ),
				'SZ' => __( 'Swaziland', 'simple-sponsorships' ),
				'SE' => __( 'Sweden', 'simple-sponsorships' ),
				'CH' => __( 'Switzerland', 'simple-sponsorships' ),
				'SY' => __( 'Syria', 'simple-sponsorships' ),
				'TW' => __( 'Taiwan', 'simple-sponsorships' ),
				'TJ' => __( 'Tajikistan', 'simple-sponsorships' ),
				'TZ' => __( 'Tanzania', 'simple-sponsorships' ),
				'TH' => __( 'Thailand', 'simple-sponsorships' ),
				'TL' => __( 'Timor-Leste', 'simple-sponsorships' ),
				'TG' => __( 'Togo', 'simple-sponsorships' ),
				'TK' => __( 'Tokelau', 'simple-sponsorships' ),
				'TO' => __( 'Tonga', 'simple-sponsorships' ),
				'TT' => __( 'Trinidad and Tobago', 'simple-sponsorships' ),
				'TN' => __( 'Tunisia', 'simple-sponsorships' ),
				'TR' => __( 'Turkey', 'simple-sponsorships' ),
				'TM' => __( 'Turkmenistan', 'simple-sponsorships' ),
				'TC' => __( 'Turks and Caicos Islands', 'simple-sponsorships' ),
				'TV' => __( 'Tuvalu', 'simple-sponsorships' ),
				'UG' => __( 'Uganda', 'simple-sponsorships' ),
				'UA' => __( 'Ukraine', 'simple-sponsorships' ),
				'AE' => __( 'United Arab Emirates', 'simple-sponsorships' ),
				'GB' => __( 'United Kingdom (UK)', 'simple-sponsorships' ),
				'US' => __( 'United States (US)', 'simple-sponsorships' ),
				'UM' => __( 'United States (US) Minor Outlying Islands', 'simple-sponsorships' ),
				'VI' => __( 'United States (US) Virgin Islands', 'simple-sponsorships' ),
				'UY' => __( 'Uruguay', 'simple-sponsorships' ),
				'UZ' => __( 'Uzbekistan', 'simple-sponsorships' ),
				'VU' => __( 'Vanuatu', 'simple-sponsorships' ),
				'VA' => __( 'Vatican', 'simple-sponsorships' ),
				'VE' => __( 'Venezuela', 'simple-sponsorships' ),
				'VN' => __( 'Vietnam', 'simple-sponsorships' ),
				'WF' => __( 'Wallis and Futuna', 'simple-sponsorships' ),
				'EH' => __( 'Western Sahara', 'simple-sponsorships' ),
				'WS' => __( 'Samoa', 'simple-sponsorships' ),
				'YE' => __( 'Yemen', 'simple-sponsorships' ),
				'ZM' => __( 'Zambia', 'simple-sponsorships' ),
				'ZW' => __( 'Zimbabwe', 'simple-sponsorships' ),
			) );
		}

		return $this->countries;
	}
}